name: Commit message policy

on:
  push:
  pull_request:

jobs:
  check-commit-messages:
    name: Check commit messages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine commit range
        id: range
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "range=${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT
          else
            echo "range=${{ github.event.before }}..${{ github.sha }}" >> $GITHUB_OUTPUT
          fi

      - name: Check commit messages
        run: |
          RANGE="${{ steps.range.outputs.range }}"
          echo "Checking commits in range: $RANGE"
          BAD=0
          # Require the tag at the start of the message: ^[ (DEV|DOC|MINOR) ]
          for sha in $(git rev-list --no-merges $RANGE 2>/dev/null || true); do
            msg=$(git log -1 --format=%B $sha)
            if ! echo "$msg" | grep -Eq '^\[(DEV|DOC|MINOR)\]'; then
              echo "Commit $sha does not start with required tag:"
              echo "$msg"
              echo "-----------------------------"
              BAD=1
            fi
          done
          if [ "$BAD" -ne 0 ]; then
            echo "::error::One or more commits do not respect the required message format. Use [DEV], [DOC] or [MINOR] at the start of the message."
            exit 1
          fi